export type PhotoEntry = {
  src: string;
  width: number;
  height: number;
  alt: string;
  world: "stories" | "brands" | "experiences";
  discipline: string;
  subject: string[];
  heroWorthy: boolean;
  hasFaces: boolean;
  mood: string;
};

export const photoCatalog: PhotoEntry[] = [
  {
    src: "/media/work/photo-1.jpeg",
    width: 1080,
    height: 1350,
    alt: "A young boy in a black tuxedo with tails walks a runway past rows of empty chairs at a fashion show.",
    world: "experiences",
    discipline: "Fashion Show Photography",
    subject: ["fashion show", "runway", "child model", "tuxedo", "event"],
    heroWorthy: true,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-2.jpeg",
    width: 980,
    height: 1224,
    alt: "A woman in a black top and leopard-print skirt smiles while holding up a paperback book titled Parenting with a Few F Words.",
    world: "stories",
    discipline: "Author Branding Portrait",
    subject: ["author", "book", "portrait", "publishing", "parenting"],
    heroWorthy: true,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-3.jpeg",
    width: 1080,
    height: 1350,
    alt: "A smiling man in glasses and a lanyard sits at a conference table with a phone, flanked by tumblers printed with a crossed-wrench shield logo.",
    world: "experiences",
    discipline: "Corporate Event Photography",
    subject: ["conference", "branded tumbler", "lanyard", "networking", "corporate"],
    heroWorthy: false,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-4.jpeg",
    width: 1080,
    height: 1350,
    alt: "A man in a blazer gestures with open arms while addressing a seated audience in a conference room, a projection screen behind him.",
    world: "experiences",
    discipline: "Conference Speaker Photography",
    subject: ["public speaking", "presentation", "audience", "conference room", "keynote"],
    heroWorthy: false,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-5.jpeg",
    width: 930,
    height: 1161,
    alt: "A smiling man with long hair, stubble, and full sleeve tattoos leans forward with clasped hands, seated by a bright window.",
    world: "stories",
    discipline: "Portrait Photography",
    subject: ["portrait", "tattoos", "casual", "smile", "indoor"],
    heroWorthy: true,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-6.jpeg",
    width: 1080,
    height: 1350,
    alt: "A man holds a microphone and speaks on stage in front of a large red banner reading 'is using the right formula', with seated attendees in the foreground.",
    world: "experiences",
    discipline: "Keynote Speaker Photography",
    subject: ["keynote", "conference", "stage", "microphone", "red banner"],
    heroWorthy: true,
    hasFaces: true,
    mood: "dramatic",
  },
  {
    src: "/media/work/photo-7.jpeg",
    width: 980,
    height: 1224,
    alt: "A group of people cut a ribbon together in front of a colorful sunrise 'Bright' logo mural, one woman wearing a pageant sash and tiara.",
    world: "experiences",
    discipline: "Ribbon-Cutting Ceremony Photography",
    subject: ["ribbon cutting", "grand opening", "community", "ceremony", "childcare"],
    heroWorthy: true,
    hasFaces: true,
    mood: "bright",
  },
  {
    src: "/media/work/photo-8.jpeg",
    width: 1080,
    height: 1350,
    alt: "Close-up of two clasped hands with a diamond wedding ring set and a black wedding band, resting on white roses and eucalyptus.",
    world: "stories",
    discipline: "Wedding Detail Photography",
    subject: ["wedding rings", "hands", "bouquet", "roses", "detail shot"],
    heroWorthy: true,
    hasFaces: false,
    mood: "quiet",
  },
  {
    src: "/media/work/photo-9.jpeg",
    width: 930,
    height: 1161,
    alt: "Exterior of the Depot #9 Saloon & Stage, a brick building with a lit sign, photographed at dusk under a colorful sky.",
    world: "brands",
    discipline: "Venue & Architecture Photography",
    subject: ["saloon", "venue exterior", "signage", "architecture", "dusk"],
    heroWorthy: true,
    hasFaces: false,
    mood: "moody",
  },
  {
    src: "/media/work/photo-10.jpeg",
    width: 1080,
    height: 1350,
    alt: "Two women look together at an open copy of the book Parenting with a Few F Words in a room with rows of blue chairs.",
    world: "stories",
    discipline: "Lifestyle Photography",
    subject: ["book", "mentorship", "reading", "two women", "indoor"],
    heroWorthy: false,
    hasFaces: true,
    mood: "quiet",
  },
  {
    src: "/media/work/photo-11.jpeg",
    width: 1080,
    height: 1350,
    alt: "A smiling man in glasses and a light blue dress shirt sits with clasped hands at a white table in front of an office window.",
    world: "stories",
    discipline: "Corporate Portrait Photography",
    subject: ["business portrait", "headshot", "office", "glasses", "professional"],
    heroWorthy: false,
    hasFaces: true,
    mood: "bright",
  },
  {
    src: "/media/work/photo-12.jpeg",
    width: 1080,
    height: 1350,
    alt: "A smiling woman in a red off-shoulder dress and dangling earrings sits at a table with red and white flowers at an evening party.",
    world: "experiences",
    discipline: "Event Portrait Photography",
    subject: ["party", "celebration", "red dress", "guest", "evening event"],
    heroWorthy: true,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-13.jpeg",
    width: 1030,
    height: 1287,
    alt: "A bearded man kneels in a meditation pose with eyes closed on a wooden dock beside a lake at sunset.",
    world: "stories",
    discipline: "Lifestyle & Wellness Photography",
    subject: ["meditation", "wellness", "sunset", "lake", "dock"],
    heroWorthy: true,
    hasFaces: true,
    mood: "quiet",
  },
  {
    src: "/media/work/photo-14.jpeg",
    width: 880,
    height: 1098,
    alt: "A man in athletic wear balances in a yoga tree pose with hands pressed together on a dock overlooking a lake and autumn trees.",
    world: "stories",
    discipline: "Lifestyle & Fitness Photography",
    subject: ["yoga", "balance", "outdoor fitness", "dock", "lake"],
    heroWorthy: true,
    hasFaces: true,
    mood: "bright",
  },
  {
    src: "/media/work/photo-15.jpeg",
    width: 780,
    height: 972,
    alt: "A woman in a bright pink dress stands beside a table with a sparkly pink birthday cake and stacked plates, decorated with a pink bow.",
    world: "experiences",
    discipline: "Birthday Event Photography",
    subject: ["birthday party", "cake", "celebration", "pink decor", "venue"],
    heroWorthy: true,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-16.jpeg",
    width: 930,
    height: 1161,
    alt: "An officiant in black robes speaks with a bride and groom holding a floral bouquet under a white and greenery wedding arch.",
    world: "experiences",
    discipline: "Wedding Ceremony Photography",
    subject: ["wedding", "officiant", "ceremony", "bouquet", "arch"],
    heroWorthy: false,
    hasFaces: true,
    mood: "quiet",
  },
  {
    src: "/media/work/photo-17.jpeg",
    width: 780,
    height: 972,
    alt: "A man in a blazer speaks and gestures to a seated group in a room with a 'Small Business' poster on the wall.",
    world: "experiences",
    discipline: "Business Seminar Photography",
    subject: ["business seminar", "speaker", "audience", "small business", "workshop"],
    heroWorthy: false,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-18.jpeg",
    width: 830,
    height: 1035,
    alt: "A smiling woman in a red tank top holds a drink can and cup while talking with another woman at an outdoor event with a banner behind them.",
    world: "experiences",
    discipline: "Outdoor Event Photography",
    subject: ["outdoor event", "drinks", "friends", "summer", "conversation"],
    heroWorthy: true,
    hasFaces: true,
    mood: "energetic",
  },
  {
    src: "/media/work/photo-19.jpeg",
    width: 930,
    height: 1161,
    alt: "Six people in formal attire pose together and smile in front of a white floral wedding arch outdoors.",
    world: "experiences",
    discipline: "Wedding Group Portrait Photography",
    subject: ["wedding guests", "family", "group photo", "formal wear", "outdoor"],
    heroWorthy: false,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-20.jpeg",
    width: 1080,
    height: 1350,
    alt: "A woman in a pink blazer sits with legs crossed on a gray office couch, smiling toward the camera.",
    world: "stories",
    discipline: "Corporate Portrait Photography",
    subject: ["business portrait", "office", "professional", "seated portrait", "confidence"],
    heroWorthy: false,
    hasFaces: true,
    mood: "bright",
  },
  {
    src: "/media/work/photo-21.jpeg",
    width: 730,
    height: 909,
    alt: "A family of five, two parents and three young children, sit together on grass under a large tree, smiling at the camera.",
    world: "stories",
    discipline: "Family Portrait Photography",
    subject: ["family", "portrait", "outdoor", "children", "tree"],
    heroWorthy: true,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-22.jpeg",
    width: 830,
    height: 1035,
    alt: "A long-haired man sings into a microphone while playing an electric guitar on stage, lit by purple stage lighting.",
    world: "experiences",
    discipline: "Live Music Photography",
    subject: ["guitarist", "singer", "concert", "stage lighting", "live music"],
    heroWorthy: true,
    hasFaces: true,
    mood: "moody",
  },
  {
    src: "/media/work/photo-23.jpeg",
    width: 930,
    height: 1161,
    alt: "A smiling man and woman, both with visible tattoos, embrace closely for a joyful close-up portrait.",
    world: "stories",
    discipline: "Couple Portrait Photography",
    subject: ["couple", "embrace", "tattoos", "smiling", "close-up"],
    heroWorthy: true,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-24.jpeg",
    width: 580,
    height: 720,
    alt: "Five women in traditional red and white Indian sarees and one in an orange dance costume pose together outdoors under bare tree branches.",
    world: "experiences",
    discipline: "Cultural Event Photography",
    subject: ["traditional dress", "saree", "group portrait", "cultural event", "dance"],
    heroWorthy: true,
    hasFaces: true,
    mood: "bright",
  },
  {
    src: "/media/work/photo-25.jpeg",
    width: 930,
    height: 1161,
    alt: "A woman in a black top and leopard-print skirt speaks and gestures to a seated audience in a room with a religious statue in the corner.",
    world: "experiences",
    discipline: "Seminar & Speaker Photography",
    subject: ["speaker", "seminar", "audience", "community talk", "faith-based event"],
    heroWorthy: false,
    hasFaces: true,
    mood: "warm",
  },
  {
    src: "/media/work/photo-26.jpeg",
    width: 930,
    height: 1161,
    alt: "A family of four and a dog lie together on grass, feet toward the camera, smiling as they lean on each other.",
    world: "stories",
    discipline: "Family Portrait Photography",
    subject: ["family", "dog", "outdoor", "casual", "children"],
    heroWorthy: true,
    hasFaces: true,
    mood: "playful",
  },
];

export type BrandTile = {
  src: string;
  kind: "logo" | "photo";
  name: string | null;
  alt: string;
};

export const brandTiles: BrandTile[] = [
  {
    src: "/media/brands/brand-1.jpeg",
    kind: "logo",
    name: "DA",
    alt: "Gold monogram logo with overlapping linear letters forming 'DA'.",
  },
  {
    src: "/media/brands/brand-2.jpeg",
    kind: "logo",
    name: "Rewind Time",
    alt: "Pink circular logo for Rewind Time Anti-Aging & Aesthetics with a cherry blossom branch design.",
  },
  {
    src: "/media/brands/brand-3.jpeg",
    kind: "logo",
    name: "FusionMix",
    alt: "Circular badge logo for FusionMix Event Bartending featuring an illustrated cocktail shaker and citrus splash.",
  },
  {
    src: "/media/brands/brand-4.jpeg",
    kind: "logo",
    name: "Dana's Events & Florals",
    alt: "Script and serif wordmark logo for Dana's Events & Florals with a small floral illustration.",
  },
  {
    src: "/media/brands/brand-5.jpeg",
    kind: "logo",
    name: "Gaels",
    alt: "Logo for Gaels Public House & Sports with a small botanical sprig above the wordmark and 'Est. 2021'.",
  },
  {
    src: "/media/brands/brand-6.jpeg",
    kind: "logo",
    name: "The KC Spa",
    alt: "Logo for The KC Spa framed by a wreath of painted watercolor flowers.",
  },
  {
    src: "/media/brands/brand-7.jpeg",
    kind: "logo",
    name: "WeCode/KC",
    alt: "Colorful logo for WeCode/KC with the tagline 'Coding a Pipeline of Future-Ready Tech Professionals' and its website URL.",
  },
  {
    src: "/media/brands/brand-8.jpeg",
    kind: "logo",
    name: "Bright Skies Childcare",
    alt: "Colorful sunburst logo for Bright Skies Childcare with playful lettering.",
  },
  {
    src: "/media/brands/brand-9.jpeg",
    kind: "logo",
    name: "The Walker Foundation",
    alt: "Navy and gold circular logo for The Walker Foundation with an ornate monogram 'W'.",
  },
  {
    src: "/media/brands/brand-10.jpeg",
    kind: "logo",
    name: "Ice Studios",
    alt: "Black, white, and pink logo for Ice Studios School of Dance with a stylized letter 'S'.",
  },
  {
    src: "/media/brands/brand-11.jpeg",
    kind: "logo",
    name: "ACA Business Club",
    alt: "Logo for ACA Business Club in green and gold with a leaf icon above the wordmark.",
  },
  {
    src: "/media/brands/brand-12.jpeg",
    kind: "logo",
    name: "Jolie Maddox",
    alt: "Elegant oval logo for Jolie Maddox, Coach & Consultant, with a signature-style script name.",
  },
  {
    src: "/media/brands/brand-13.jpeg",
    kind: "logo",
    name: "Toastmasters International",
    alt: "Blue and gold globe logo for Toastmasters International.",
  },
  {
    src: "/media/brands/brand-14.jpeg",
    kind: "logo",
    name: "Compass",
    alt: "Minimalist black wordmark logo for the real estate company Compass.",
  },
  {
    src: "/media/brands/brand-15.jpeg",
    kind: "logo",
    name: "Sonic",
    alt: "Blue and red bow-tie shaped logo for the Sonic drive-in restaurant chain.",
  },
  {
    src: "/media/brands/brand-16.jpeg",
    kind: "logo",
    name: "Cadillac",
    alt: "Cadillac crest emblem in silver, red, and gold.",
  },
  {
    src: "/media/brands/brand-17.jpeg",
    kind: "logo",
    name: "Hallmark",
    alt: "Purple script wordmark logo for Hallmark with a small crown above the lettering.",
  },
];
