import manifest from "./portfolio-manifest.json";

/**
 * The portfolio — JP's own photography, organised into chapters ("acts").
 *
 * Images come from `portfolio-manifest.json`, generated by
 * `npm run portfolio:build` from the original camera files. The pipeline owns
 * the technical fields (dimensions, blur, colour); `alt`, `chapter` and
 * `featured` are editorial and written by hand/review — the build preserves
 * them on re-run.
 *
 * FACTUAL INTEGRITY: alt text describes only what is visible in the frame.
 * No client names, venues, dates or outcomes are attached to any photo.
 */

export type ChapterId =
  | "stage"
  | "nights"
  | "gatherings"
  | "vows"
  | "faces"
  | "open-air"
  | "places"
  | "details";

export type Chapter = {
  id: ChapterId;
  /** "I", "II"… — the act number shown on screen. */
  numeral: string;
  title: string;
  /** Short line under the title. Describes the kind of work, never a claim. */
  line: string;
};

export const CHAPTERS: Chapter[] = [
  { id: "stage", numeral: "I", title: "Stage", line: "Light, sound and the second a performance lands." },
  { id: "nights", numeral: "II", title: "Nights", line: "Red carpets, arrivals and rooms dressed for the evening." },
  { id: "gatherings", numeral: "III", title: "Gatherings", line: "Rooms full of people showing up for each other." },
  { id: "vows", numeral: "IV", title: "Vows", line: "Promises, and the people who came to witness them." },
  { id: "faces", numeral: "V", title: "Faces", line: "Portraits that look like the person, on a good day." },
  { id: "open-air", numeral: "VI", title: "Open Air", line: "Families, kids and dogs, outside and unposed." },
  { id: "places", numeral: "VII", title: "Places", line: "Homes and spaces, from the doorway and from the air." },
  { id: "details", numeral: "VIII", title: "Details", line: "The table, the cake, the thing in someone's hands." },
];

export type PortfolioImage = {
  id: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait" | "square";
  blur: string;
  color: string;
  alt: string;
  chapter: ChapterId;
  /** Hand-picked for the chapter reels and the opening tunnel. */
  featured: boolean;
};

type RawEntry = {
  id: string;
  width: number;
  height: number;
  orientation: PortfolioImage["orientation"];
  blur: string;
  color: string;
  alt?: string;
  chapter?: ChapterId;
  featured?: boolean;
};

const CHAPTER_IDS = new Set(CHAPTERS.map((c) => c.id));

/** Only fully catalogued frames are published — an image with no alt text never ships. */
export const portfolio: PortfolioImage[] = (manifest as RawEntry[])
  .filter((e): e is RawEntry & { alt: string; chapter: ChapterId } =>
    Boolean(e.alt && e.chapter && CHAPTER_IDS.has(e.chapter)),
  )
  .map((e) => ({
    id: e.id,
    width: e.width,
    height: e.height,
    orientation: e.orientation,
    blur: e.blur,
    color: e.color,
    alt: e.alt,
    chapter: e.chapter,
    featured: Boolean(e.featured),
  }));

export type ImageSize = "sm" | "md" | "lg";

export const portfolioSrc = (id: string, size: ImageSize) => `/media/portfolio/${size}/${id}.webp`;

/** `srcset` across the three renditions, with real widths for the given image. */
export function portfolioSrcSet(img: Pick<PortfolioImage, "id" | "width" | "height">) {
  const longEdge = Math.max(img.width, img.height);
  const w = (edge: number) => Math.round((img.width / longEdge) * Math.min(edge, longEdge));
  return [
    `${portfolioSrc(img.id, "sm")} ${w(480)}w`,
    `${portfolioSrc(img.id, "md")} ${w(1200)}w`,
    `${portfolioSrc(img.id, "lg")} ${w(2200)}w`,
  ].join(", ");
}

export const imagesByChapter = (id: ChapterId) => portfolio.filter((p) => p.chapter === id);

/** Chapters that actually have published frames, in act order. */
export const activeChapters = CHAPTERS.filter((c) => portfolio.some((p) => p.chapter === c.id));
